version: 0.2
phases:
  install:
    runtime-versions:
        docker: 18
    pre_build:
    commands:
      - aws --version
      # - echo Logging in to Amazon ECR...
      # - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - echo Installing node modules ...
      - npm i
      # - echo Running tests ...
      # - npm run test
      - echo Building ... | tee -a log.txt
      - npm run build
artifacts:
  files:
    - '*'
    - '**/*'
  name: stagingBuildFile
  base-directory: build
